version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: Postgres
    environment:
      POSTGRES_USER: 'agent'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'trello'
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
volumes:
  data:
